---
title: "Histogramme des distances au transect et cartes d'occurrence"
author: "Léa Pautrel"
output:
  html_document:
    highlight: zenburn
    number_sections: no
    theme: yeti
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	fig.align = "Center",
	message = FALSE,
	warning = FALSE
)

# Packages
library(dplyr)
library(spatstat)
library(ggplot2) ; ggplot2::theme_set(theme_light())
library(foreign)			# read.dbf
library(ggmap)
library(wesanderson)
library(tibble)
```

------------------------------------

# Importation des données
```{r import_donnees}
load("../data/effort_output.RData")
# effort_ouput : Effort data divided in multiple sub-data differing by their scale of study.

load("../data/list_prepare_obs_by_sp.RData")
# list_prepare_obs_by_sp : observation data divided in multiple sub-data differing by their scale of study.

load("../data/predata_output.RData")
# predata_output : A grid of 2km cells size with different covariable associated around the observation.

gridata <- read.dbf("../data/SPEE_CAPECET_Grid2km_modified.dbf")
# gridata : equivalent to predata from predata_output but with a extended surface
```

## Dates des sessions
```{r}
data.frame(session = effort_output$segdata$session, date = effort_output$segdata$date) %>% 
	unique() %>% 
	as.tibble() %>% 
	arrange(session, date)
```

# Histogramme des distances au transect
```{r fig.height = 4}
list_prepare_obs_by_sp$PRIGLA_obs_output$obsdata %>% 
  ggplot(aes(x = distance)) +
  geom_histogram(bins = 10)
```

# Cartes d'occurrences
```{r}
data_occ <- list_prepare_obs_by_sp$PRIGLA_obs_output$distdata %>%
	filter(detected == 1)
segdata <- effort_output$segdata

# Emplacement
sbbox <- make_bbox(lon = c(min(data_occ$longitude), max(data_occ$longitude)),
									 lat = c(min(data_occ$latitude), max(data_occ$latitude)),
									 f = 0.8)

# Création de la carte vide
zone_obs <- get_map(location = sbbox,
										zoom = 8,
										maptype =  "terrain")

zone_obs_map = ggmap(zone_obs) + theme_void()

zone_obs_map +
	geom_path(
		data = segdata,
		mapping = aes(x = longitude, y = latitude, group = Transect.Label),
		size = 0.3,
		colour = alpha("black", 0.2)
	) +
	geom_point(data = data_occ,
						 aes(x = longitude,
						 		y = latitude,
						 		col = session)) +
	scale_color_manual(values = wesanderson::wes_palette("BottleRocket1", n = 4))
```

