---
title: "Appropriation des données"
subtitle: "Histogramme des distances au transect et fonction de détection"
author: "Léa Pautrel"
output:
  html_document:
    highlight: zenburn
    number_sections: yes
    theme: yeti
    toc: yes
---

```{r setup, include=FALSE}
rm(list=ls())

knitr::opts_chunk$set(
	echo = FALSE,
	fig.align = "center",
	message = FALSE,
	warning = FALSE,
	error = TRUE
)

# Packages
library(dplyr)				# tidyverse
library(foreign)			# read.dbf
library(DT)						# interactive HTML datatables

## Graphes packages
library(ggplot2) ; ggplot2::theme_set(theme_light())

## Packages calcul
library(Rdistance)
library(dsm)
```

------------------------------------
# `dsm` : exemple dauphins
Importation données
```{r}
set.seed(11123)
data(mexdolphins)
```

## Fonction de détection
### Sans cov
```{r}
library(Distance)
detfc.hr.null <-
	Distance::ds(distdata,
							 max(distdata$distance),
							 key = "hr",
							 adjustment = NULL)
```


```{r}
summary(detfc.hr.null)
par(mfrow=c(1,2))
plot(detfc.hr.null, showpoints=FALSE, pl.den=0, lwd=2)
ddf.gof(detfc.hr.null$ddf)
```

### Avec cov
```{r}
detfc.hr.beau <-
	ds(
		distdata,
		max(distdata$distance),
		formula =  ~ as.factor(beaufort),
		key = "hr",
		adjustment = NULL
	)
```

```{r}
summary(detfc.hr.beau)
class(detfc.hr.beau)
```
### Avec RDistance
```{r}
dfunc.null <- Rdistance::dfuncEstim(
	formula = distance ~ 1,
	detectionData = distdata,
	siteData = distdata,
	likelihood = "hazrate",
	pointSurvey = FALSE
)
summary(dfunc.null)
class(dfunc.null)
```


## dsm
* les données doivent être segmentées
```{r}
dsm.xy <- dsm(count ~ s(x, y), 
							detfc.hr.null,
							segdata,
							obsdata,
							method = "REML")
summary(dsm.xy)
```

```{r}
vis.gam(
	dsm.xy,
	plot.type = "contour",
	view = c("x", "y"),
	asp = 1,
	type = "response",
	contour.col = "black",
	n.grid = 100
)
```

### Cov depth
```{r}
dsm.xy.depth <-
	dsm(count ~ s(x, y, k = 10) + s(depth, k = 20),
			detfc.hr.null, # fonction de détection sans covariable
			segdata,
			obsdata,
			method = "REML")
summary(dsm.xy.depth)
vis.gam(
	dsm.xy.depth,
	plot.type = "contour",
	view = c("x", "y"),
	asp = 1,
	type = "response",
	contour.col = "black",
	n.grid = 100
)
plot(dsm.xy.depth, select=2)
```
### pred abondance
```{r}
dsm.xy.pred <- predict(dsm.xy, preddata, preddata$area)
summary(dsm.xy.pred)
```


