---
title: "Appropriation des données"
subtitle: "Test avec nos donnees"
author: "Emma ROUAULT"
output:
  html_document:
    highlight: zenburn
    number_sections: yes
    theme: yeti
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	fig.align = "center",
	message = FALSE,
	warning = FALSE,
	error = TRUE
)

# Packages
library(dplyr)				# tidyverse
library(foreign)			# read.dbf
library(DT)						# interactive HTML datatables

## Graphes packages
library(ggplot2) ; ggplot2::theme_set(theme_light())

## Packages calcul
library(Rdistance)
library(dsm)
```
# Importation des données
```{r import_donnees}
load(file.path(here::here(), "PRIGLA_envrt(avec thons)/data/effort_output.RData"))
# effort_ouput : Effort data divided in multiple sub-data differing by their scale of study.

load(file.path(here::here(), "PRIGLA_envrt(avec thons)/data/list_prepare_obs_by_sp.RData"))
# list_prepare_obs_by_sp : observation data divided in multiple sub-data differing by their scale of study.

load(file.path(here::here(), "PRIGLA_envrt(avec thons)/data/predata_output.RData"))
# predata_output : A grid of 2km cells size with different covariable associated around the observation.

gridata <- read.dbf(file.path(here::here(), "PRIGLA_envrt(avec thons)/data/SPEE_CAPECET_Grid2km_modified.dbf"))
# gridata : equivalent to predata from predata_output but with a extended surface
```
------------------------------------
## Fonction de détection
### Sans cov
```{r}
library(Distance)
detfc.hr.null <-
	Distance::ds(list_prepare_obs_by_sp$PRIGLA_obs_output$obsdata,
							 max(list_prepare_obs_by_sp$PRIGLA_obs_output$obsdata$distance),
							 key = "hr",
							 adjustment = NULL)
```


```{r}
summary(detfc.hr.null)
par(mfrow=c(1,2))
plot(detfc.hr.null, showpoints=FALSE, pl.den=0, lwd=2)
ddf.gof(detfc.hr.null$ddf)
```

### Avec cov
```{r}
detfc.hr.sea <-
	ds(
		list_prepare_obs_by_sp$PRIGLA_obs_output$distdata,
		max(list_prepare_obs_by_sp$PRIGLA_obs_output$distdata$seaState),
		formula =  ~ as.factor(seaState),
		key = "hr",
		adjustment = NULL
	)
```

```{r}
summary(detfc.hr.sea)
class(detfc.hr.sea)
```
### Avec RDistance
```{r}
dfunc.null <- Rdistance::dfuncEstim(
	formula = distance ~ 1,
	detectionData = list_prepare_obs_by_sp$PRIGLA_obs_output$distdata,
	siteData = list_prepare_obs_by_sp$PRIGLA_obs_output$distdata,
	likelihood = "hazrate",
	pointSurvey = FALSE
)
summary(dfunc.null)
class(dfunc.null)
```


## dsm
* les données doivent être segmentées
```{r}
dsm.xy <- dsm(count ~ s(list_prepare_obs_by_sp$PRIGLA_obs_output$distdata$longitude), 
							detfc.hr.null,
							list_prepare_obs_by_sp$PRIGLA_obs_output$segdata,
							list_prepare_obs_by_sp$PRIGLA_obs_output$obsdata,
							method = "REML")
summary(dsm.xy)
```

```{r}
vis.gam(
	dsm.xy,
	plot.type = "contour",
	view = c("x", "y"),
	asp = 1,
	type = "response",
	contour.col = "black",
	n.grid = 100
)
```

