---
title: "nykanen"
author: "Rindra"
date: "14/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(sf)
library(here)
library(foreign) 
library(lubridate)
library(ggmap)
library(Rdistance)
library(cowplot)
```

```{r}
obsdata <- read_excel("C:/Users/rindr/Downloads/obsdata.xlsx")
distdata <- read_excel("C:/Users/rindr/Downloads/segdata.xlsx", sheet = "Shark sightings")
##là on a les covariables et tout
##prepdist c'est la distance
segdata <- read_excel("C:/Users/rindr/Downloads/segdata.xlsx", sheet = "Effort segments")
```

```{r}
library(ggmap)
library(ggplot2)
data_occ <- obsdata %>% 
	filter(detected == 1)

# Emplacement
sbbox <- make_bbox(lon = c(min(distdata$Lon), max(distdata$Lon)),
									 lat = c(min(distdata$Lat), max(distdata$Lat)),
									 f = 1)

# Création de la carte vide
zone_obs <- get_map(location = sbbox,
										zoom = 5,
										maptype =  "terrain")

zone_obs_map = ggmap(zone_obs) + theme_void()

zone_obs_map + geom_point(data = distdata,
														aes(x = Lon,
																y = Lat,
																col = Substratum))
```


FONCTION DE DETECTION
Variable Cloud2
```{r}
obsdata <- as.data.frame(obsdata)
detfc.hr.cloud <- Distance::ds(obsdata,
							 max(obsdata$distance),
							 formula = ~ Cloud2,
							 key = "hr",
							 adjustment = NULL)
```


```{r}
summary(detfc.hr.cloud)
par(mfrow=c(1,2))
plot(detfc.hr.cloud, showpoints=FALSE, pl.den=0, lwd=2)
ddf.gof(detfc.hr.cloud$ddf)
```



```{r}
availability <- as.vector(obsdata$availability)   
```


```{r}
seg$Sample.label <- 
dsm.all.tw <- dsm(abundance.est~s(x,y) + s(Turbidity), 
                  detfc.hr.cloud, segdata, obsdata, method = "REML", 
                  family = tw(), engine = "gam", select = T, 
                  group = T, gamma = 1.4, 
                  availability = availability)
```

