---
title: "test_data"
subtitle: "TEST JEU DE DONNÉES PLOS"
author: "Emma ROUAULT"
output:
  html_document:
    highlight: zenburn
    number_sections: yes
    theme: yeti
    toc: yes
---

```{r setup, include=FALSE}
rm(list=ls())

knitr::opts_chunk$set(
	echo = TRUE,
	fig.align = "center",
	message = FALSE,
	warning = FALSE,
	error = TRUE
)

# Packages
library(dplyr)				# tidyverse
library(foreign)			# read.dbf
library(DT)						# interactive HTML datatables

## Graphes packages
library(ggplot2) ; ggplot2::theme_set(theme_light())

## Packages calcul
library(Distance)
library(dsm)
```


------------------------------------

Importation des données

```{r import_donnees}
obsdata<-read_excel("/Users/emmarouault/Documents/Agrocampus/2020:2021/requins/data_ucc/obsdata.xlsx")
segdata<-read_excel("/Users/emmarouault/Documents/Agrocampus/2020:2021/requins/data_ucc/segdata.xlsx",sheet="Effort segments")
distdata<-read_excel("/Users/emmarouault/Documents/Agrocampus/2020:2021/requins/data_ucc/segdata.xlsx",sheet="Shark sightings")
```

Cart représentation occurence requins 

```{r}
library(ggplot2)
library(ggmap)
data_occ <- obsdata %>%
	filter(detected == 1)

# Emplacement
sbbox <- make_bbox(lon = c(min(obsdata$long), max(obsdata$long)),
									 lat = c(min(obsdata$lat), max(obsdata$lat)),
									 f = 1)

# Création de la carte vide
zone_obs <- get_map(location = sbbox,
										zoom = 5,
										maptype =  "terrain")

zone_obs_map = ggmap(zone_obs) + theme_void()

zone_obs_map + geom_point(data = distdata,
														aes(x = Lon,
																y = Lat,
																col = Substratum))
```


# Sans aucune covariables

## Fonction de détection
```{r}
obsdata<-as.data.frame(obsdata)
detfc.null <- Distance::ds(obsdata,
							 max(obsdata$distance),
							 key = "hr",
							 adjustment = NULL)
```


```{r}
summary(detfc.null)
par(mfrow=c(1,2))
plot(detfc.null, showpoints=FALSE, pl.den=0, lwd=2)
ddf.gof(detfc.null$ddf)
```



## Fonction de detection avec covariable cloud

### Avec cov, fonction de detection
```{r}
detfc.hr.cloud <-
	ds(obsdata,
		max(obsdata$distance),
		formula =  ~ Cloud2,
		key = "hr",
		adjustment = NULL
	)
```

```{r}
summary(detfc.hr.cloud)
class(detfc.hr.cloud)
```
## Fonction de densité

```{r}
availability <- as.vector(obsdata$availability)  
dsm.all.tw <- dsm(abundance.est~s(x,y) + s(depth) + s(slope) + s(dist_land), detfc.hr.cloud, segdata, obsdata, method = "REML", family = tw(), engine = "gam", select = T, group = T, gamma = 1.4, availability = availability)

dsm.xy <- dsm(count ~ s(X, Y), 
							detfc.null,
							segdata,
							obsdata,
							method = "REML")
summary(dsm.xy)
```