---
title: "test_data"
subtitle: "TEST JEU DE DONNÉES PLOS"
author: "Emma ROUAULT"
output:
  html_document:
    highlight: zenburn
    number_sections: yes
    theme: yeti
    toc: yes
---

```{r setup, include=FALSE}
rm(list=ls())

knitr::opts_chunk$set(
	echo = TRUE,
	fig.align = "center",
	message = FALSE,
	warning = FALSE,
	error = TRUE
)

# Packages
library(dplyr)				# tidyverse
library(foreign)			# read.dbf
library(DT)						# interactive HTML datatables
library(readxl)

## Graphes packages
library(ggplot2) ; ggplot2::theme_set(theme_light())
library(ggmap)
library(plotly)
library(RColorBrewer)

## Packages calcul
library(Distance)
library(dsm)
```


------------------------------------

Importation des données

```{r import_donnees}
obsdata <- as.data.frame(read_excel("../data_ucc/obsdata.xlsx"))
segdata <- as.data.frame(read_excel("../data_ucc/segdata.xlsx", sheet = "Effort segments"))
distdata <- as.data.frame(read_excel("../data_ucc/segdata.xlsx", sheet = "Shark sightings"))
```

Cart représentation occurence requins 

```{r, fig.height=10}
data_occ <- obsdata %>%
	filter(detected == 1)

# Emplacement
sbbox <- make_bbox(lon = c(min(obsdata$long), max(obsdata$long)),
									 lat = c(min(obsdata$lat), max(obsdata$lat)),
									 f = 0.4)

# Création de la carte vide
zone_obs <- get_map(location = sbbox,
										zoom = 6,
										maptype =  "terrain")
```


```{r, fig.height=10, fig.width=8}
zone_obs_map = ggmap(zone_obs) + theme_void()

carte_finale <- zone_obs_map +
	geom_path(
		data = distdata,
		mapping = aes(x = Lon, y = Lat, group = ID),
		size = 0.3,
		colour = alpha("black", 0.2)
	) +
	geom_point(data = distdata,
						 aes(x = Lon,
						 		y = Lat,
						 		col = as.factor(Year)),
						 size = 2) +
	scale_color_manual(values = wesanderson::wes_palette("BottleRocket1", n = 4))

carte_finale
```

# Sans aucune covariables
## Fonction de détection
```{r}
obsdata <- as.data.frame(obsdata)
detfc.null <- Distance::ds(obsdata,
													 max(obsdata$distance),
													 key = "hr",
													 adjustment = NULL)


summary(detfc.null)
par(mfrow = c(1, 2))
plot(detfc.null,
		 showpoints = FALSE,
		 pl.den = 0,
		 lwd = 2)
ddf.gof(detfc.null$ddf)
```

## Fonction de detection avec covariable cloud
### Avec cov, fonction de detection
```{r}
detfc.hr.cloud <-
	ds(obsdata,
		max(obsdata$distance),
		formula =  ~ Cloud2,
		key = "hr",
		adjustment = NULL
	)

summary(detfc.hr.cloud)
class(detfc.hr.cloud)
par(mfrow = c(1, 2))
plot(detfc.hr.cloud,
		 showpoints = FALSE,
		 pl.den = 0,
		 lwd = 2)
ddf.gof(detfc.hr.cloud$ddf)
```


```{r}
availability <- as.vector(obsdata$availability)

dsm.all.tw <-
	dsm(formula =	abundance.est ~ s(x, y) + s(depth) + s(slope) + 
			s(dist_land) + s(dist_200) +  s(mld_2015) + s(sst_2015) + s(chl_2015),
		detfc.hr.cloud,
		segment.data = segdata,
		observation.data = obsdata,
		method = "REML",
		family = tw(),
		engine = "gam",
		select = T,
		group = T,
		gamma = 1.4,
		availability = availability
	)
```

